PrivateKey = {Path = "./aggregator.keystore", Password = "testonly"}

[L1]
WsURL = "<URL>"     # CHANGE THIS: use the URL of your L1 node
RpcURL = "<URL>"  # CHANGE THIS: use the URL of your L1 node
CDKValidiumAddress = "0x3509953a690bdDe964eBA9b4621642e86B228CDe"
DataCommitteeAddress = "0xfa412719ba053008FbB0850b7605A92d000Fd8B6"
Timeout = "3m"
RetryPeriod = "5s"
BlockBatchSize = 32

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"
Password = "committee_password"
Name = "committee_db"
Host = "127.0.0.1"
Port = "5434"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 50062
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
EnableL2SuggestedGasPricePolling = false
	[RPC.WebSockets]
		Enabled = false
